
# tap repositories and their packages

tap homebrew/core
brew ack
brew activemq
brew apktool
brew autoconf
brew automake
brew cmake
brew coreutils
brew csvkit
brew dcraw
brew diff-so-fancy
brew dos2unix
brew exiftool
brew faac
brew fasd
brew fdk-aac
brew fdupes
brew ffmpeg
brew freetype
brew gdbm
brew gettext
brew gifify
brew git
brew gnu-sed
brew go
brew groovysdk
brew hashcat
brew hub
brew icu4c
brew imagemagick
brew iperf
brew ipmitool
brew jasper
brew jemalloc
brew jenv
brew jpeg
brew jq
brew kompose
brew kubernetes-helm
brew lame
brew libav
brew libevent
brew libidn2
brew libogg
brew libpng
brew libsass
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvo-aacenc
brew libvorbis
brew libvpx
brew libvterm
brew little-cms2
brew lua
brew luajit
brew mad
brew mas
brew maven
brew mercurial
brew moreutils
brew msgpack
brew neovim
brew netperf
brew nginx
brew nmap
brew oniguruma
brew openjpeg
brew openssl
brew openssl@1.1
brew opus
brew pcre
brew pdftohtml
brew pkg-config
brew python
brew readline
brew reattach-to-user-namespace
brew redis
brew rsync
brew sdl2
brew snappy
brew sox
brew sqlite
brew ssh-copy-id
brew tcping
brew testssl
brew texi2html
brew theora
brew tig
brew tmux
brew tree
brew unibilium
brew utf8proc
brew vim --with-lua
brew wakeonlan
brew webp
brew wget
brew x264
brew x265
brew xvid
brew xz
brew yasm
brew zplug

tap argon/mas

tap caskroom/cask

tap caskroom/drivers

tap caskroom/versions

tap jenkins-x/jx
brew jx

tap kyounger/file
brew brew-file

# Other Homebrew packages
brew kubectl
brew phantomjs
brew python3

# Other Cask applications
cask adium
cask alfred
cask android-file-transfer
cask android-platform-tools
cask appcleaner
cask balsamiq-mockups
cask bartender
cask bettertouchtool
cask charles
cask cyberduck
cask firefox
cask flux
cask google-chrome
cask google-cloud-sdk
cask intellij-idea
cask iterm2
cask java
cask java8
cask kaleidoscope
cask karabiner-elements
cask kode54-cog
cask macdown
cask macvim
cask quicklook-csv
cask rocket
cask sequel-pro
cask shortcat
cask slack
cask sqlworkbenchj
cask ui-browser
cask unpkg
cask vlc
cask vmware-fusion
cask wireshark

# Additional files
file ./Brewfile.local
