tap kyounger/file
tap homebrew/versions
tap homebrew/dupes
tap homebrew/core
tap caskroom/versions
tap caskroom/cask
tap argon/mas
cask wireshark
cask vmware-fusion
cask vlc
cask unpkg
cask ui-browser
cask tunnelblick
cask sqlworkbenchj
cask shotcut
cask shortcat
cask sequel-pro
cask mysqlworkbench
cask macvim
cask macdown
cask kodi
cask karabiner
cask kaleidoscope
cask jollysfastvnc
cask iterm2
cask hugin
cask google-drive
cask google-chrome
cask flux
cask firefox
cask dropbox
cask cyberduck
cask carbon-copy-cloner
cask bettertouchtool
cask balsamiq-mockups
cask appcleaner
cask android-file-transfer
cask alfred
cask adobe-creative-cloud
cask adium
brew youtube-dl
brew yasm
brew xz
brew xvid
brew x264
brew wget
brew vim --with-lua
brew tmux
brew tig
brew texi2html
brew ssh-copy-id
brew sqlite
brew rsync
brew reattach-to-user-namespace
brew readline
brew python
brew pkg-config
brew pcre
brew openssl
brew node4-lts
brew nmap
brew nginx
brew netperf
brew moreutils
brew mercurial
brew maven32
brew maven
brew mas
brew lua
brew little-cms2
brew libvo-aacenc
brew libtool
brew libtiff
brew libpng
brew libevent
brew libav
brew lame
brew jq
brew jpeg
brew jasper
brew ipmitool
brew iperf
brew imagemagick
brew hub
brew git
brew gettext
brew gdbm
brew freetype
brew ffmpeg --with-faac
brew fasd
brew faac
brew exiftool
brew docker
brew dcraw
brew brew-file
brew apktool
brew activemq
brew ack
