#!/bin/sh

# osacompile -x -e 'tell application "System Events" to set volume input volume 0' -o ~/bin/mute_mic.scpt
# osacompile -x -e 'tell application "System Events" to set volume input volume 100' -o ~/bin/unmute_mic.scpt

osacompile -x -o ~/bin/mute_mic.scpt ./mute_mic.applescript
osacompile -x -o ~/bin/unmute_mic.scpt ./unmute_mic.applescript
