# use the fix for pbpaste/pbcopy, see: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
set-option -g default-command "safe-reattach-to-user-namespace -l $SHELL"

# using `C-a, y`, this puts the copied tmux buffer in the osx clipboard
bind y run-shell "safe-reattach-to-user-namespace -l $SHELL -c 'tmux showb | pbcopy'"
# use <prefix>-P to copy buffer to a file
bind P command-prompt -p 'save history to filename:' -I '~/tmux.history' 'capture-pane -S -99999 ; save-buffer %1 ; delete-buffer'

# use vim motion keys while in copy mode
setw -g mode-keys vi

#default terminal
set -g default-terminal "screen-256color"

# Automatically set window title
setw -g automatic-rename on

# start tab numbering at 1, not 0
set -g base-index 1

# this helps with vim: https://github.com/tmux-plugins/vim-tmux-focus-events
set -g focus-events on

# Sane scrolling
# Note: the more I think about this, the less I want to use it. Left for historical reasons
# set -g terminal-overrides 'xterm*:smcup@:rmcup@'

#set option globally to use Control-a as command prefix key
set-option -g prefix C-a
bind a send-prefix

# Highlight active window
set-window-option -g window-status-current-bg red

bind C-a last-window

unbind C-Left
unbind C-Right
bind -r Left select-window -t :-
bind -r Right select-window -t :+
bind -r h select-window -t :-
bind -r l select-window -t :+

unbind % # Remove default binding since we're replacing
bind | split-window -h
bind - split-window -v

# Set status bar
set -g status-bg black
set -g status-fg white
set -g status-left '#[fg=green]#H'
set -g status-right '#[fg=yellow]#(uptime | cut -d " " -f 1-4 /proc/loadavg)'

# Set window notifications
# setw -g monitor-activity on
# set -g visual-activity on

# Set practically unlimited history
set -g history-limit 99999

# use Control key + the vim motion keys to move between panes
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind k clear-history



# Faster Escape Sequence Time
set -s escape-time 0

# Aggresive Resize
setw -g aggressive-resize on

# r = tmux renumbering script, courtesy of: http://brainscraps.wikia.com/wiki/Renumbering_tmux_Windows
unbind r
bind r run-shell "safe-reattach-to-user-namespace -l $SHELL -c '~/bin/tmux_renum'"
# bind r run "~/bin/tmux_renum"

#TODO: read comments here: http://robots.thoughtbot.com/post/19398560514/how-to-copy-and-paste-with-tmux-on-mac-os-x

# set -g status-left-length 52
# set -g status-right-length 451
# set -g status-fg white
# set -g status-bg colour234
# set -g window-status-activity-attr bold
# set -g pane-border-fg colour245
# set -g pane-active-border-fg colour39
# set -g message-fg colour16
# set -g message-bg colour221
# set -g message-attr bold
# set -g status-left '#[fg=colour235,bg=colour252,bold] ❐ #S #[fg=colour252,bg=colour238,nobold]⮀#[fg=colour245,bg=colour238,bold] #(whoami) #[fg=colour238,bg=colour234,nobold]⮀'
# set -g window-status-format "#[fg=white,bg=colour234] #I #W "
# set -g window-status-current-format "#[fg=colour234,bg=colour39]⮀#[fg=colour25,bg=colour39,noreverse,bold] #I ⮁ #W #[fg=colour39,bg=colour234,nobold]⮀"

# Alternate Theme for shells without Inconsolata-dz-Powerline:
# set -g status-left ' #[bold]❐ #S#[default] ⣿'
# set -g status-right '#[bold]#(whoami) ● #H#[default] ⡇ #[fg=blue]%H:%M#[default] ']



# This template will allow you to test for OSX, and include a source if it is
# if-shell 'test "$(uname)" = "Darwin"' 'source ~/.tmux-osx.conf'
