# todo: https://github.com/christoomey/vim-tmux-navigator
# set -ga terminal-overrides ',*:Tc' # this is for 256 color
# set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q' # this is for the cursor shape
set -g base-index 1
setw -g automatic-rename on
setw -g mode-keys vi
set -g display-time 2000

set -g prefix C-a
bind a send-prefix
bind C-a last-window

# using `C-a, y`, this puts the copied tmux buffer in the osx clipboard
bind y run-shell "safe-reattach-to-user-namespace -l $SHELL -c 'tmux showb | pbcopy'"
# use <prefix>-P to copy buffer to a file
bind P command-prompt -p 'save history to filename:' -I '~/tmux.history' 'capture-pane -S -99999 ; save-buffer %1 ; delete-buffer'

#repeatable key bind for window selection
bind -r h select-window -t :-
bind -r l select-window -t :+

unbind % # Remove default binding since we're replacing
bind | split-window -h
bind - split-window -v

# use Control key + the vim motion keys to move between panes
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind k clear-history

# r = tmux renumbering script, courtesy of: http://brainscraps.wikia.com/wiki/Renumbering_tmux_Windows
unbind r
bind r run-shell "safe-reattach-to-user-namespace -l $SHELL -c '~/bin/tmux_renum'"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'thewtex/tmux-mem-cpu-load'

set -g @themepack 'powerline/block/red2'

set -g @prefix_highlight_prefix_prompt 'Wait'
set -g @prefix_highlight_copy_prompt 'Copy'
set -g @prefix_highlight_sync_prompt 'Sync'
set -g @prefix_highlight_empty_prompt '      '
set -g @prefix_highlight_bg colour235
set -g @prefix_highlight_fg white
set -g @powerline-color-grey-1 colour235
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=white,bg=default'

set -g @themepack-status-left-area-left-format "#S"
set -g @themepack-status-left-area-middle-format "#I:#P"
set -g @themepack-status-left-area-right-format "#{prefix_highlight}"
# set -g @themepack-status-right-area-left-format "#[fg=colour245]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --interval 2)#[default]"
set -g @themepack-status-right-area-left-format ""
set -g @themepack-status-right-area-middle-format "%Y-%m-%d"
set -g @themepack-status-right-area-right-format "#(whoami)@#H"
set -g @themepack-window-status-current-format "#I:#W#F"
set -g @themepack-window-status-format "#I:#W#F"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
