# set -ga terminal-overrides ',*:Tc' # this is for 256 color
# set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q' # this is for the cursor shape
set -g base-index 1
setw -g automatic-rename on
setw -g mode-keys vi

set -g prefix C-a
bind a send-prefix
bind C-a last-window

# using `C-a, y`, this puts the copied tmux buffer in the osx clipboard
bind y run-shell "safe-reattach-to-user-namespace -l $SHELL -c 'tmux showb | pbcopy'"
# use <prefix>-P to copy buffer to a file
bind P command-prompt -p 'save history to filename:' -I '~/tmux.history' 'capture-pane -S -99999 ; save-buffer %1 ; delete-buffer'

#repeatable key bind for window selection
bind -r h select-window -t :-
bind -r l select-window -t :+

unbind % # Remove default binding since we're replacing
bind | split-window -h
bind - split-window -v

# use Control key + the vim motion keys to move between panes
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind k clear-history

# r = tmux renumbering script, courtesy of: http://brainscraps.wikia.com/wiki/Renumbering_tmux_Windows
unbind r
bind r run-shell "safe-reattach-to-user-namespace -l $SHELL -c '~/bin/tmux_renum'"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/block/red'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
